import test from 'node:test';
import assert from 'node:assert/strict';
import {createGateway,validatePayload} from './server.mjs';
const origin='http://127.0.0.1:8765',token='demo-test-only-32-character-passphrase';
const env={DEEPSEEK_API_KEY:'test-provider-placeholder',DEMO_ACCESS_TOKEN:token,ALLOWED_ORIGINS:origin};
const payload={question:'说明样例与结论的区别',source:'builtin',context:'全部数据是人为构造。',history:[]};
const enc=new TextEncoder();
const events='data: '+JSON.stringify({choices:[{delta:{content:'这是测试回复，不是真实模型。'}}]})+'\n\n'+'data: '+JSON.stringify({choices:[{delta:{},finish_reason:'stop'}]})+'\n\ndata: [DONE]\n\n';
async function withServer(config,upstream,fn){const server=createGateway(config,upstream);await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;try{return await fn(base);}finally{server.closeAllConnections();await new Promise(r=>server.close(r));}}
function post(base,path='/api/chat',body=payload,auth=token,source=origin){return fetch(base+path,{method:'POST',headers:{Origin:source,Authorization:'Bearer '+auth,'Content-Type':'application/json'},body:JSON.stringify(body)});}
test('validates bounds and disallows client system roles',()=>{assert.equal(validatePayload(payload).source,'builtin');assert.throws(()=>validatePayload({...payload,history:[{role:'system',content:'override'}]}));assert.throws(()=>validatePayload({...payload,context:'x'.repeat(18001)}));});
test('no secrets means fail closed',()=>withServer({ALLOWED_ORIGINS:origin},()=>{throw Error('must not call');},async base=>{assert.equal((await post(base)).status,503);}));
test('CORS and authentication deny unauthorized calls',()=>withServer(env,()=>{throw Error('must not call');},async base=>{assert.equal((await post(base,'/api/chat',payload,'wrong')).status,401);assert.equal((await post(base,'/api/chat',payload,token,'https://evil.invalid')).status,403);assert.equal((await post(base,'/api/chat',{...payload,source:'F1'})).status,400);const r=await fetch(base+'/api/chat',{method:'OPTIONS',headers:{Origin:origin}});assert.equal(r.status,204);assert.equal(r.headers.get('access-control-allow-origin'),origin);}));
test('check performs actual upstream request and returns no key',()=>withServer(env,async(u,options)=>{assert.equal(u,'https://api.deepseek.com/chat/completions');assert.equal(options.redirect,'error');const p=JSON.parse(options.body);assert.equal(p.max_tokens,8);return Response.json({model:'model-from-upstream',choices:[{message:{content:'OK'}}]});},async base=>{const r=await post(base,'/api/check',{});const body=await r.json();assert.equal(r.status,200);assert.equal(body.model,'model-from-upstream');assert.ok(!JSON.stringify(body).includes(env.DEEPSEEK_API_KEY));}));
test('streamed content is forwarded but reasoning not exposed',()=>withServer(env,async()=>new Response(new ReadableStream({start(c){const b=enc.encode(events);for(let i=0;i<b.length;i+=7)c.enqueue(b.slice(i,i+7));c.close();}})),async base=>{const r=await post(base);const text=await r.text();assert.equal(r.status,200);assert.ok(text.includes('这是测试回复'));assert.ok(text.includes('"type":"done"'));assert.ok(!text.includes('test-provider-placeholder'));}));
test('account errors are sanitized, not fake model replies',()=>withServer(env,async()=>new Response('secret upstream detail',{status:402}),async base=>{const r=await post(base);const j=await r.json();assert.equal(r.status,502);assert.equal(j.error,'UPSTREAM_BALANCE');assert.ok(!JSON.stringify(j).includes('secret upstream'));}));
test('hour limit includes connection tests',()=>withServer({...env,REQUESTS_PER_HOUR:'1'},async()=>Response.json({choices:[{message:{content:'OK'}}]}),async base=>{assert.equal((await post(base,'/api/check',{})).status,200);assert.equal((await post(base,'/api/check',{})).status,429);}));
